---
title: "data_checking_demo"
author: "Jennie Sun"
date: "5/25/2021"
output: html_document
---

```{r}
pacman::p_load(rio, plyr, foreach, dplyr, openxlsx, chron, tidyverse, reshape, xlsx)
```

```{r}
#load demographic data
demographic_tbl <- 
  import("INSERT FILE PATH HERE")  %>%
  filter(!is.na(demographicid))

colnames(demographic_tbl) <- tolower(colnames(demographic_tbl))
#create skip codes list
skipcodes <- c(990:999)
```

Data frame summarizing number of NAs in each column: 
```{r}
count_NA_demo <- sapply(demographic_tbl, function(x) sum(is.na(x)))
count_NA_demo <- as.data.frame(count_NA_demo)
```

* YES_NO_CHOICES
```{r}
yes_no_codes <- c(0:1)
yes_no_var_index_demo <- 
  filter(demographic_tbl, !individualenrolled%in%c(yes_no_codes, skipcodes)) %>%
           select(household, individualenrolled)
  filter(demographic_tbl, !householdhead%in%c(yes_no_codes, skipcodes)) %>%
           select(household, householdhead)
  filter(demographic_tbl, !individualunwell%in%c(yes_no_codes, skipcodes)) %>%
           select(household, individualunwell) 

print(paste0("Values out of range for variables with Yes/No choices for Household ID", yes_no_var_index_demo$household))
print(yes_no_var_index_demo)
```

* GENDER_CHOICES (used in Demographics and Death tables)
```{r}
gender_codes <- c(1:2) # +skip codes
gender_index <- 
    filter(demographic_tbl, !individualgender%in%c(gender_codes, skipcodes)) %>%
           select(household, individualgender)
print(gender_index)
```

* EDUCATION_LEVEL_CHOICES
```{r}
educ_codes <- c(0:5) # +skip codes
educ_index <- 
    filter(demographic_tbl, !individualedlevel%in%c(educ_codes, skipcodes)) %>%
           select(household, individualedlevel)
print(educ_index)
```

* RELATIONSHIP_CHOICES
```{r}
relationship_codes <- c(0:13) # +skip codes
relationship_index <- 
    filter(demographic_tbl, !relationhhh%in%c(relationship_codes, skipcodes)) %>%
           select(household, relationhhh)
print(relationship_index)
```


```{r}
individualdays_codes <- c(0:31)

individualdays_index <-
filter(demographic_tbl, !individualdaysunwell%in%c(individualdays_codes, skipcodes)) %>%
           select(household, individualdaysunwell)
  filter(demographic_tbl, !individuallostdays%in%c(individualdays_codes, skipcodes)) %>%
           select(household, individuallostdays)

print(paste0("Values out of range (0:31) for individualdaysunwell and individuallostdays for Household ID", individualdays_index$household))
print(individualdays_index)
```

```{r}
individualage_codes <- c(0:150)

individualage_index <-
filter(demographic_tbl, !individualage%in%c(individualage_codes, skipcodes)) %>%
           select(household, individualage)


print(paste0("Values out of range (0:150) for individualage for Household ID", individualage_index$household))
print(individualage_index)
```


```{r}
error_dat <- join_all(list(yes_no_var_index_demo, gender_index, educ_index, relationship_index, individualdays_index, individualage_index),
  by="household", type='full')

error_dat_reshaped <- melt(error_dat, na.rm = TRUE, id = "household")
out_tab <- data.frame(cbind(error_dat_reshaped, error_msg='Value out of range'))
```
write.xlsx(out_tab, "demographic_tbl_erroneous_entries.xlsx")
