---
title: "data_checking_NonMarineOrg"
author: "Jennie Sun"
date: "6/1/2021"
output: html_document
---
```{r}
library(tidyverse)
library(reshape)
library(xlsx)
pacman::p_load(rio, plyr, foreach, dplyr, openxlsx, chron)
```

```{r}
#load wwf nonmarine org data
non_marine_org_wwf <- 
  import('./BHS_UNIPA_WWF_2016-19_Data_for_Comparison/WWF_data/nonmarineorganizationmembership-20210113.csv')  %>%
  filter(!is.na(nmorganizationid))
colnames(non_marine_org_wwf) <- tolower(colnames(non_marine_org_wwf))
#create skip codes list
skipcodes <- c(990:999)
```

Data frame summarizing number of NAs in each column: 
```{r}
count_NA_non_marine_org <- sapply(non_marine_org_wwf, function(x) sum(is.na(x)))
count_NA_non_marine_org <- as.data.frame(count_NA_non_marine_org)
```

* ORGANIZATION_POSITION_CHOICES (`position`)
```{r}
org_pos_codes <- c(1:2)
org_pos_index_non_marine <- 
  filter(non_marine_org_wwf, !position%in%c(org_pos_codes, skipcodes)) %>%
           select(nmorganizationid, position) %>%
  filter(!is.na(position))

print(paste0("Values out of range for variables with Organization Position choices for Non-Marine Organization ID", org_pos_index_non_marine$nmorganizationid))
print(org_pos_index_non_marine)
```

* YES_NO_CHOICES (`meeting`)
```{r}
yes_no_codes <- c(0:1)
yes_no_var_index_non_marine <- 
  filter(non_marine_org_wwf, !meeting%in%c(yes_no_codes, skipcodes)) %>%
           select(nmorganizationid, meeting) %>%
  filter(!is.na(meeting))

print(paste0("Values out of range for variables with Yes/No choices for Non-Marine Organization ID", yes_no_var_index_non_marine$nmorganizationid))
print(yes_no_var_index_non_marine)
```